// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oovafszgxwubkgymvawh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vdmFmc3pneHd1YmtneW12YXdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzQ4ODQsImV4cCI6MjA2OTkxMDg4NH0.ncyMmgzYM68ADGJYqox7W0e7O8AHzdpn6sblAoAz_BM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});